# Generated by Django 5.2.2 on 2025-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Model',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=255)),
                ('techDescription', models.TextField()),
            ],
            options={
                'db_table': 'modelinmenu',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=255)),
                ('domainDescription', models.TextField()),
            ],
            options={
                'db_table': 'domaininmenu',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelId', models.AutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=255)),
                ('levelDescription', models.TextField()),
            ],
            options={
                'db_table': 'levelinmenu',
            },
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'login_details',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dOB', models.CharField(max_length=255)),
                ('dOJ', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pNumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recruiter',
            },
        ),
        migrations.CreateModel(
            name='RecruiterArch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dOB', models.CharField(max_length=255)),
                ('dOJ', models.CharField(max_length=255)),
                ('dOL', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pNumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recruiter_archive',
            },
        ),
        migrations.CreateModel(
            name='SkillsInMenu',
            fields=[
                ('skillID', models.AutoField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(max_length=255)),
                ('skillDescription', models.TextField()),
            ],
            options={
                'db_table': 'skillsinmenu',
            },
        ),
        migrations.CreateModel(
            name='TechInMenu',
            fields=[
                ('techId', models.AutoField(primary_key=True, serialize=False)),
                ('techName', models.CharField(max_length=255)),
                ('techDescription', models.TextField()),
            ],
            options={
                'db_table': 'techinmenu',
            },
        ),
        migrations.CreateModel(
            name='UsageDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usageDateTime', models.DateTimeField()),
                ('techOpt', models.CharField(max_length=255)),
                ('skillOpt', models.CharField(max_length=255)),
                ('jD_given', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'usage_details',
            },
        ),
    ]
