# Generated by Django 5.2.2 on 2025-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
