# Generated by Django 5.2.2 on 2025-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_logindetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='yrsExperience',
            fields=[
                ('yrsId', models.AutoField(primary_key=True, serialize=False)),
                ('yrsexp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'yrsexp',
            },
        ),
    ]
