# Generated by Django 5.2.2 on 2025-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_yrsexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagedetails',
            name='jD_given',
        ),
        migrations.AddField(
            model_name='usagedetails',
            name='file_1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usagedetails',
            name='file_2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
